# Generated by Django 5.2.3 on 2025-11-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='messagetemplate',
            table=None,
        ),
    ]
