# Generated by Django 5.2.3 on 2025-11-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_interaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('base_product_id', models.IntegerField()),
                ('recommended_product_id', models.IntegerField()),
                ('recommendation_type', models.CharField(max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pest_recommendations',
            },
        ),
    ]
